/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStopsRouteImport } from './routes/_authenticated/stops'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated/sos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated/schools'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedParentsRouteImport } from './routes/_authenticated/parents'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedGeofencesRouteImport } from './routes/_authenticated/geofences'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChildrenRouteImport } from './routes/_authenticated/children'
import { Route as AuthenticatedCheckinsRouteImport } from './routes/_authenticated/checkins'
import { Route as AuthenticatedBusesRouteImport } from './routes/_authenticated/buses'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAbsencesRouteImport } from './routes/_authenticated/absences'
import { Route as AuthenticatedTripsLiveRouteImport } from './routes/_authenticated/trips.live'
import { Route as AuthenticatedTripsHistoryRouteImport } from './routes/_authenticated/trips.history'
import { Route as AuthenticatedRoutesRouteIdStopsRouteImport } from './routes/_authenticated/routes.$routeId.stops'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStopsRoute = AuthenticatedStopsRouteImport.update({
  id: '/stops',
  path: '/stops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentsRoute = AuthenticatedParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGeofencesRoute = AuthenticatedGeofencesRouteImport.update({
  id: '/geofences',
  path: '/geofences',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChildrenRoute = AuthenticatedChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckinsRoute = AuthenticatedCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBusesRoute = AuthenticatedBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAbsencesRoute = AuthenticatedAbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsLiveRoute = AuthenticatedTripsLiveRouteImport.update({
  id: '/trips/live',
  path: '/trips/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsHistoryRoute =
  AuthenticatedTripsHistoryRouteImport.update({
    id: '/trips/history',
    path: '/trips/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoutesRouteIdStopsRoute =
  AuthenticatedRoutesRouteIdStopsRouteImport.update({
    id: '/$routeId/stops',
    path: '/$routeId/stops',
    getParentRoute: () => AuthenticatedRoutesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/buses': typeof AuthenticatedBusesRoute
  '/checkins': typeof AuthenticatedCheckinsRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/geofences': typeof AuthenticatedGeofencesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/schools': typeof AuthenticatedSchoolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sos': typeof AuthenticatedSosRoute
  '/stops': typeof AuthenticatedStopsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/trips/history': typeof AuthenticatedTripsHistoryRoute
  '/trips/live': typeof AuthenticatedTripsLiveRoute
  '/routes/$routeId/stops': typeof AuthenticatedRoutesRouteIdStopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/buses': typeof AuthenticatedBusesRoute
  '/checkins': typeof AuthenticatedCheckinsRoute
  '/children': typeof AuthenticatedChildrenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/geofences': typeof AuthenticatedGeofencesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/schools': typeof AuthenticatedSchoolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sos': typeof AuthenticatedSosRoute
  '/stops': typeof AuthenticatedStopsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/trips/history': typeof AuthenticatedTripsHistoryRoute
  '/trips/live': typeof AuthenticatedTripsLiveRoute
  '/routes/$routeId/stops': typeof AuthenticatedRoutesRouteIdStopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/absences': typeof AuthenticatedAbsencesRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/buses': typeof AuthenticatedBusesRoute
  '/_authenticated/checkins': typeof AuthenticatedCheckinsRoute
  '/_authenticated/children': typeof AuthenticatedChildrenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/geofences': typeof AuthenticatedGeofencesRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/parents': typeof AuthenticatedParentsRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/_authenticated/schools': typeof AuthenticatedSchoolsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/stops': typeof AuthenticatedStopsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/trips/history': typeof AuthenticatedTripsHistoryRoute
  '/_authenticated/trips/live': typeof AuthenticatedTripsLiveRoute
  '/_authenticated/routes/$routeId/stops': typeof AuthenticatedRoutesRouteIdStopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/absences'
    | '/alerts'
    | '/analytics'
    | '/assignments'
    | '/buses'
    | '/checkins'
    | '/children'
    | '/dashboard'
    | '/drivers'
    | '/geofences'
    | '/logs'
    | '/notifications'
    | '/organizations'
    | '/parents'
    | '/routes'
    | '/schools'
    | '/settings'
    | '/sos'
    | '/stops'
    | '/users'
    | '/trips/history'
    | '/trips/live'
    | '/routes/$routeId/stops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/absences'
    | '/alerts'
    | '/analytics'
    | '/assignments'
    | '/buses'
    | '/checkins'
    | '/children'
    | '/dashboard'
    | '/drivers'
    | '/geofences'
    | '/logs'
    | '/notifications'
    | '/organizations'
    | '/parents'
    | '/routes'
    | '/schools'
    | '/settings'
    | '/sos'
    | '/stops'
    | '/users'
    | '/trips/history'
    | '/trips/live'
    | '/routes/$routeId/stops'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/_authenticated/absences'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/assignments'
    | '/_authenticated/buses'
    | '/_authenticated/checkins'
    | '/_authenticated/children'
    | '/_authenticated/dashboard'
    | '/_authenticated/drivers'
    | '/_authenticated/geofences'
    | '/_authenticated/logs'
    | '/_authenticated/notifications'
    | '/_authenticated/organizations'
    | '/_authenticated/parents'
    | '/_authenticated/routes'
    | '/_authenticated/schools'
    | '/_authenticated/settings'
    | '/_authenticated/sos'
    | '/_authenticated/stops'
    | '/_authenticated/users'
    | '/_authenticated/trips/history'
    | '/_authenticated/trips/live'
    | '/_authenticated/routes/$routeId/stops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stops': {
      id: '/_authenticated/stops'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof AuthenticatedStopsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/geofences': {
      id: '/_authenticated/geofences'
      path: '/geofences'
      fullPath: '/geofences'
      preLoaderRoute: typeof AuthenticatedGeofencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/children': {
      id: '/_authenticated/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AuthenticatedChildrenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkins': {
      id: '/_authenticated/checkins'
      path: '/checkins'
      fullPath: '/checkins'
      preLoaderRoute: typeof AuthenticatedCheckinsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buses': {
      id: '/_authenticated/buses'
      path: '/buses'
      fullPath: '/buses'
      preLoaderRoute: typeof AuthenticatedBusesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/absences': {
      id: '/_authenticated/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AuthenticatedAbsencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/live': {
      id: '/_authenticated/trips/live'
      path: '/trips/live'
      fullPath: '/trips/live'
      preLoaderRoute: typeof AuthenticatedTripsLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/history': {
      id: '/_authenticated/trips/history'
      path: '/trips/history'
      fullPath: '/trips/history'
      preLoaderRoute: typeof AuthenticatedTripsHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routes/$routeId/stops': {
      id: '/_authenticated/routes/$routeId/stops'
      path: '/$routeId/stops'
      fullPath: '/routes/$routeId/stops'
      preLoaderRoute: typeof AuthenticatedRoutesRouteIdStopsRouteImport
      parentRoute: typeof AuthenticatedRoutesRoute
    }
  }
}

interface AuthenticatedRoutesRouteChildren {
  AuthenticatedRoutesRouteIdStopsRoute: typeof AuthenticatedRoutesRouteIdStopsRoute
}

const AuthenticatedRoutesRouteChildren: AuthenticatedRoutesRouteChildren = {
  AuthenticatedRoutesRouteIdStopsRoute: AuthenticatedRoutesRouteIdStopsRoute,
}

const AuthenticatedRoutesRouteWithChildren =
  AuthenticatedRoutesRoute._addFileChildren(AuthenticatedRoutesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAbsencesRoute: typeof AuthenticatedAbsencesRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedBusesRoute: typeof AuthenticatedBusesRoute
  AuthenticatedCheckinsRoute: typeof AuthenticatedCheckinsRoute
  AuthenticatedChildrenRoute: typeof AuthenticatedChildrenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedGeofencesRoute: typeof AuthenticatedGeofencesRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedParentsRoute: typeof AuthenticatedParentsRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRouteWithChildren
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedStopsRoute: typeof AuthenticatedStopsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedTripsHistoryRoute: typeof AuthenticatedTripsHistoryRoute
  AuthenticatedTripsLiveRoute: typeof AuthenticatedTripsLiveRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAbsencesRoute: AuthenticatedAbsencesRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedBusesRoute: AuthenticatedBusesRoute,
  AuthenticatedCheckinsRoute: AuthenticatedCheckinsRoute,
  AuthenticatedChildrenRoute: AuthenticatedChildrenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedGeofencesRoute: AuthenticatedGeofencesRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedParentsRoute: AuthenticatedParentsRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRouteWithChildren,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedStopsRoute: AuthenticatedStopsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedTripsHistoryRoute: AuthenticatedTripsHistoryRoute,
  AuthenticatedTripsLiveRoute: AuthenticatedTripsLiveRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
